title: Evan Moriarty
author: Evan Moriarty
email: epringle365@vivaldi.net
description: > # this means to ignore newlines until "show_exerpts:"
  Evan Moriarty - A self-taught web developer with a passion to make the internet fascinating

show_excerpts: false # set to true to show excerpts on the homepage
url: https://evanmoriarty.com/
minima:
  # Minima date format
  # refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    email: epringle365@vivaldi.net
    twitter: evan_eboy
    github:  SrgSprinkles
    # rss: rss
    # dribbble: sprinfo
    instagram: evan.eboy
    stackoverflowuser: SrgSprinkles
    stackoverflowlink: 8493023/srgsprinkles
    buymeacoffee: sprinfo

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - home.md
 - about.md
 - blog.md

blogurl: /blog/

# Build settings
theme: minima

# Kramdown is the markdown render
# - auto_ids generates ids for headers in blog
kramdown:
  auto_ids: true

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

permalink: /blog/:categories/:title:output_ext
