title: Evan Moriarty
author: Evan Moriarty
email: epringle365@vivaldi.net
description: > # this means to ignore newlines until "show_exerpts:"
  Evan Moriarty - A self-taught web developer with a passion to make the internet fascinating

show_excerpts: false # set to true to show excerpts on the homepage
url: https://evanmoriarty.com/

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - home.md
 - about.md
 - blog.md

# Blog related
blogurl: /blog/
date_format: "%b %-d, %Y"

# Kramdown is the markdown render
# - auto_ids generates ids for headers in blog
kramdown:
  auto_ids: true

sass:
  sass_dir: _sass

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

permalink: /blog/:categories/:title:output_ext
